core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('shop.urls'), name='index'),
    path('orders/', include('orders.urls', namespace='orders')),

]

shop/urls.py
from django.urls import path

from .views import ProductsListView, IndexView, basket_add, basket_delete

app_name = 'shop'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product_list/', ProductsListView.as_view(), name='product_list'),
    path('category/<int:category_id>/', ProductsListView.as_view(), name='category'),
    path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),
    path('<slug:category_slug>/', ProductsListView.as_view(), name='product_list_by_category'),
    path('basket/add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket/delete/<int:basket_id>/', basket_delete, name='basket_delete'),
]

shop/models.py
from django.db import models
from django.urls import reverse

from accounts.models import User

class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True,
                            verbose_name='Название категории')
    slug = models.SlugField(max_length=150, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE,
                                 verbose_name='Выберите категорию'
                                 )
    name = models.CharField(max_length=200, db_index=True, verbose_name='Наименование')
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='static/images/', blank=True, verbose_name='Фото')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='Цена')
    available = models.BooleanField(default=True, verbose_name='Наличие')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name
    

class BasketQuerySet(models.QuerySet):
     def total_sum(self):
          return sum(basket.sum() for basket in self)
     
     def total_quantity(self):
          return sum(basket.quantity for basket in self)


class Basket(models.Model):
     user = models.ForeignKey(to=User, on_delete=models.CASCADE)
     product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
     quantity = models.PositiveSmallIntegerField(default=0)
     created_timestamp = models.DateTimeField(auto_now_add=True)

     objects = BasketQuerySet.as_manager()

     def __str__(self):
          return f'Корзина для {self.user.username} | Продукт: {self.product.name}' 
     
     def sum(self):
          return self.product.price * self.quantity


     

shop/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect


from .models import Category, Product, Basket


class IndexView(TemplateView):
    template_name = "shop/index.html"


class ProductsListView(ListView):
    model = Product
    template_name = 'shop/products.html'
    paginate_by = 3

    def get_queryset(self):
        queryset = super(ProductsListView, self).get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data()
        context['categories'] = Category.objects.all()
        return context



@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_delete(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

templates/shop/index.html
{% extends 'base.html' %}

{% block content %}

<body>

    <!-- Page Content -->
    <section>
        <!--    <div class="alert alert-light text-center" role="alert">-->
        <!--        Информационное сообщение-->
        <!--    </div>-->
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">Store</h1>
                    <p>
                        Новые образы и лучшие бренды на Store.
                        Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="product_list">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>



</body>

</html>

{% endblock %}

templates/shop/products.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<title>Store Каталог</title>

<body>

    

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">Store</h1>
                <div class="list-group">
                    {% for category in categories %}
                    <a href="{% url 'shop:category' category.id %}" class="list-group-item">
                        {{ category.name }}</a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static '/img/slides/slide-1.jpg' %}"
                                alt="First slide">
                        </div>
                        
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static '/img/slides/slide-2.jpg' %}"
                                alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static '/img/slides/slide-3.jpg' %}"
                                alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">
                    {% for product in object_list %}
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="#">
                                <img class="card-img-top" src="{{ product.image.url }}" alt="">
                            </a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="#">{{ product.name }}</a>
                                </h4>
                                <h5>{{ product.price }}</h5>
                                <p class="card-text">{{ product.description }}</p>
                            </div>
                            <div class="card-footer text-center">
                                <a class="btn btn-outline-success" 
                                href="{% url 'shop:basket_add' product.id %}">
                                    Отправить в корзину
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% if is_paginated %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                                <a class="page-link" 
                                href="{% if page_obj.has_previous %} {% url 'shop:paginator' page_obj.previous_page_number %} {% else %} # {% endif %}" 
                                tabindex="-1" aria-disabled="true">Предыдущая</a>
                            </li>
                            {% for page in paginator.page_range %}
                                <li class="page-item">
                                    <a class="page-link" href="{% url 'shop:paginator' page %}">
                                        {{ page }}
                                    </a>
                                </li>
                            {% endfor %}
                            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                                <a class="page-link" href="{% if page_obj.has_next %} {% url 'shop:paginator' page_obj.next_page_number %} {% else %} # {% endif %}">Следующая</a>
                            </li>
                        </ul>
                    </nav>
                {% endif %}

            </div>

        </div>

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Store 2022</p>
        </div>
        <!-- /.container -->
    </footer>

{% endblock %}

</body>

</html>